/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Padrao = IDL.Record({
  'volatilidade' : IDL.Float64,
  'volume' : IDL.Float64,
  'compressao' : IDL.Float64,
  'distMediaMovel' : IDL.Float64,
  'aceleracao' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const Ativo = IDL.Record({
  'volume' : IDL.Float64,
  'variacao' : IDL.Float64,
  'score' : IDL.Float64,
  'preco' : IDL.Float64,
  'symbol' : IDL.Text,
});

export const idlService = IDL.Service({
  'calcularScore' : IDL.Func([Padrao], [IDL.Float64], ['query']),
  'getAtivos' : IDL.Func([], [IDL.Vec(Ativo)], ['query']),
  'getPadroes' : IDL.Func([], [IDL.Vec(Padrao)], ['query']),
  'limparDados' : IDL.Func([], [], []),
  'salvarAtivos' : IDL.Func([IDL.Vec(Ativo)], [], []),
  'salvarPadrao' : IDL.Func([Padrao], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Padrao = IDL.Record({
    'volatilidade' : IDL.Float64,
    'volume' : IDL.Float64,
    'compressao' : IDL.Float64,
    'distMediaMovel' : IDL.Float64,
    'aceleracao' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const Ativo = IDL.Record({
    'volume' : IDL.Float64,
    'variacao' : IDL.Float64,
    'score' : IDL.Float64,
    'preco' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  
  return IDL.Service({
    'calcularScore' : IDL.Func([Padrao], [IDL.Float64], ['query']),
    'getAtivos' : IDL.Func([], [IDL.Vec(Ativo)], ['query']),
    'getPadroes' : IDL.Func([], [IDL.Vec(Padrao)], ['query']),
    'limparDados' : IDL.Func([], [], []),
    'salvarAtivos' : IDL.Func([IDL.Vec(Ativo)], [], []),
    'salvarPadrao' : IDL.Func([Padrao], [], []),
  });
};

export const init = ({ IDL }) => { return []; };